# --- Installing stage
FROM node:11.4 AS installer

WORKDIR /usr/src/app

ARG NODE_ENV=production
ARG NPM_TOKEN=
ENV NODE_ENV=${NODE_ENV}

RUN npm install --global typescript

COPY package*.json ./

RUN npm install

# --- Building stage
FROM installer AS builder

WORKDIR /usr/src/app

COPY ./src src
COPY tsconfig.json ./
RUN npm run build

EXPOSE 8070

CMD ["node","dist/server.js"]